In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/hogwarts_sorting.csv")
df.head()

,Blood Status,Bravery,Intelligence,Loyalty,Ambition,Dark Arts Knowledge,Quidditch Skills,Dueling Skills,Creativity,House
0,Half-blood,9,4,7,5,0,8,8,7,Gryffindor
1,Muggle-born,6,8,5,7,5,6,4,9,Ravenclaw
2,Pure-blood,1,4,7,7,1,4,4,6,Hufflepuff
3,Pure-blood,9,1,3,4,1,9,10,1,Gryffindor
4,Muggle-born,5,9,7,3,3,6,7,9,Ravenclaw

In [4]:
df.shape

(1000, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Blood Status         1000 non-null   object
 1   Bravery              1000 non-null   int64
 2   Intelligence         1000 non-null   int64
 3   Loyalty              1000 non-null   int64
 4   Ambition             1000 non-null   int64
 5   Dark Arts Knowledge  1000 non-null   int64
 6   Quidditch Skills     1000 non-null   int64
 7   Dueling Skills       1000 non-null   int64
 8   Creativity           1000 non-null   int64
 9   House                1000 non-null   object
dtypes: int64(8), object(2)
memory usage: 78.3+ KB

In [ ]:
df.describe()

,Bravery,Intelligence,Loyalty,Ambition,Dark Arts Knowledge,Quidditch Skills,Dueling Skills,Creativity
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,5.026000,5.28100,5.129000,5.136000,4.040000,5.46000,6.223000,5.208000
std,2.682633,2.66179,2.695111,2.716041,3.112248,2.74881,2.833249,2.730969
min,1.000000,1.00000,1.000000,1.000000,0.000000,0.00000,1.000000,1.000000
25%,3.000000,3.00000,3.000000,3.000000,1.000000,4.00000,4.000000,3.000000
50%,5.000000,5.00000,5.000000,5.000000,3.000000,6.00000,7.000000,5.000000
75%,7.000000,7.00000,7.000000,7.000000,7.000000,7.00000,9.000000,7.000000
max,10.000000,10.00000,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000

In [ ]:
df.columns

Index(['Blood Status', 'Bravery', 'Intelligence', 'Loyalty', 'Ambition',
       'Dark Arts Knowledge', 'Quidditch Skills', 'Dueling Skills',
       'Creativity', 'House'],
      dtype='object')

In [ ]:
df.dtypes

Blood Status           object
Bravery                 int64
Intelligence            int64
Loyalty                 int64
Ambition                int64
Dark Arts Knowledge     int64
Quidditch Skills        int64
Dueling Skills          int64
Creativity              int64
House                  object
dtype: object